title: Yixin Zou
url: "https://yixinzou.github.io"
baseurl: ""

markdown: kramdown
# ins_logo: "./logo.jpg"

tracking_id: #

footer: yes
footer_text: |
  <p style="text-align: center;">
    <a href="mailto:firstname.lastname@mpi-sp.org">Email</a> |
    <a href="https://scholar.google.com/citations?user=ukyCsPAAAAAJ">Google Scholar</a> |
    <a href="https://www.linkedin.com/in/yixinzou">LinkedIn</a>
  </p>
  <div style="height: 40px;"></div>

sass:
    style: compressed
    sass_dir: _sass

nav:
  - name: "Bio"
    link: /"bio/"
  - name: "Publications"
    link: "/publications/"
  - name: "Group"
    link: "/group/"
  - name: "Service"
    link: "/service/"


