title: Yixin Zou
url: "https://yixinzou.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
# footer_url: "https://github.com/ankitsultana"
footer_text: |
  <p>
    <a href="mailto:firstname.lastname@mpi-sp.org">Email</a> |
    <a href="https://scholar.google.com/citations?user=ukyCsPAAAAAJ">Google Scholar</a> |
    <a href="https://www.linkedin.com/in/yixinzou">LinkedIn</a>
  </p>

sass:
    style: compressed
    sass_dir: _sass

nav:
  - name: "Bio"
    link: "bio/"
  - name: "Publications"
    link: "/publications/"
  - name: "Group"
    link: "/group/"
# - name: "Resources"
#    link: "/resources/"
# - name: "Service"
#    link: "/service/"


